export interface Pool {
  id: number
  rank: number
  name: string
  hotel: string
  location: string
  country: string
  region: string
  image: string
  rating: number
  reviewCount: number
  features: string[]
  description: string
  sources: string[]
  awards?: string[]
  kidFriendly: boolean
  websiteUrl: string
  bookingUrl?: string
  slug: string
}

export function generateSlug(hotel: string, id: number): string {
  const base = hotel
    .toLowerCase()
    .replace(/['']/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
  return `${base}-${id}`
}

// Data researched from: Condé Nast Traveler, Travel + Leisure, The Luxury Travel Expert, 
// The Rooftop Guide, TripAdvisor Travelers' Choice, and other authoritative travel publications.

export const pools: Pool[] = [
  {
    id: 1,
    rank: 1,
    name: "Caldera Infinity Pool",
    hotel: "Grace Santorini",
    location: "Imerovigli, Santorini",
    country: "Greece",
    region: "Europe",
    image: "/images/pool-grace-santorini.jpg",
    rating: 9.8,
    reviewCount: 2847,
    features: ["Infinity Edge", "Caldera View", "Heated", "Adults Only"],
    description: "The largest infinity pool in Santorini, perched high above the Caldera with uninterrupted views across to the volcanic islands. Voted one of the world's most romantic pool settings.",
    sources: ["Condé Nast Traveler", "The Luxury Travel Expert", "Travel + Leisure"],
    awards: ["CNT Gold List 2025", "World's Best Hotel Pool"],
    kidFriendly: false,
    websiteUrl: "https://www.gracehotels.com/santorini",
    bookingUrl: "https://www.gracehotels.com/santorini/reservations"
  },
  {
    id: 2,
    rank: 2,
    name: "SkyPark Infinity Pool",
    hotel: "Marina Bay Sands",
    location: "Marina Bay",
    country: "Singapore",
    region: "Asia",
    image: "/images/pool-marina-bay-sands.jpg",
    rating: 9.7,
    reviewCount: 15420,
    features: ["Rooftop", "City Skyline", "150m Length", "57 Stories High"],
    description: "The world's longest elevated infinity pool at 150 meters, perched nearly 200 meters above sea level. An architectural marvel offering 360° views of the Singapore skyline.",
    sources: ["The Rooftop Guide", "Travel + Leisure", "Guinness World Records"],
    awards: ["World's Longest Rooftop Pool", "Most Instagrammed Pool"],
    kidFriendly: true,
    websiteUrl: "https://www.marinabaysands.com/sands-skypark/infinity-pool.html",
    bookingUrl: "https://www.marinabaysands.com/hotel/rooms-suites.html"
  },
  {
    id: 3,
    rank: 3,
    name: "Three-Tier Infinity Pool",
    hotel: "Amankila",
    location: "Manggis, Bali",
    country: "Indonesia",
    region: "Asia",
    image: "/images/pool-amankila-bali.jpg",
    rating: 9.6,
    reviewCount: 1256,
    features: ["Three-Tier Design", "Ocean View", "Balinese Architecture", "Infinity Edge"],
    description: "Inspired by the water palace at nearby Ujung, this spectacular pool cascades in three tiers down the hillside, reminiscent of a rice paddy, overlooking the Lombok Strait.",
    sources: ["The Luxury Travel Expert", "Condé Nast Traveler"],
    awards: ["#2 Most Beautiful Pool in the World"],
    websiteUrl: "https://www.aman.com/resorts/amankila",
    bookingUrl: "https://www.aman.com/resorts/amankila/offers"
  },
  {
    id: 4,
    rank: 4,
    name: "Cliffside Infinity Pool",
    hotel: "Hotel du Cap-Eden-Roc",
    location: "Cap d'Antibes",
    country: "France",
    region: "Europe",
    image: "/images/pool-hotel-du-cap.jpg",
    rating: 9.6,
    reviewCount: 3102,
    features: ["Saltwater", "Heated", "Mediterranean View", "Historic"],
    description: "An iconic heated saltwater pool carved into the rocks of the French Riviera, overlooking the breathtaking Mediterranean. A seven-time Condé Nast Traveler Readers' Choice winner.",
    sources: ["Condé Nast Traveler", "Travel + Leisure"],
    awards: ["CNT Readers' Choice 2017-2025", "CNT Gold List 2024"],
    websiteUrl: "https://www.oetkercollection.com/hotels/hotel-du-cap-eden-roc/",
    bookingUrl: "https://www.oetkercollection.com/hotels/hotel-du-cap-eden-roc/booking/"
  },
  {
    id: 5,
    rank: 5,
    name: "Desert Escarpment Pool",
    hotel: "Amangiri",
    location: "Canyon Point, Utah",
    country: "USA",
    region: "Americas",
    image: "/images/pool-amangiri-utah.jpg",
    rating: 9.5,
    reviewCount: 1890,
    features: ["Desert Setting", "Natural Rock", "Infinity Edge", "Stunning Architecture"],
    description: "Set within a sunken courtyard framed by a dramatic rock escarpment, this pool blends seamlessly into the otherworldly Utah desert landscape. The epitome of desert luxury.",
    sources: ["The Luxury Travel Expert", "Condé Nast Traveler", "Travel + Leisure"],
    awards: ["#5 Most Beautiful Pool in the World", "Best Wilderness Resort"],
    websiteUrl: "https://www.aman.com/resorts/amangiri",
    bookingUrl: "https://www.aman.com/resorts/amangiri/offers"
  },
  {
    id: 6,
    rank: 6,
    name: "Amalfi Infinity Pool",
    hotel: "Monastero Santa Rosa Hotel & Spa",
    location: "Amalfi Coast",
    country: "Italy",
    region: "Europe",
    image: "/images/pool-monastero-amalfi.jpg",
    rating: 9.5,
    reviewCount: 987,
    features: ["Cliffside", "Freshwater", "Garden Terraces", "Tyrrhenian Sea View"],
    description: "Carved into the rock-base cliff and surrounded by four levels of lush gardens, this freshwater infinity pool overlooks the clear blue Tyrrhenian Sea and stunning Amalfi coastline.",
    sources: ["Condé Nast Traveler"],
    awards: ["CNT Readers' Choice 2018-2025"]
  },
  {
    id: 7,
    rank: 7,
    name: "Ravello Sky Pool",
    hotel: "Belmond Hotel Caruso",
    location: "Ravello, Amalfi Coast",
    country: "Italy",
    region: "Europe",
    image: "/images/pool-belmond-caruso.jpg",
    rating: 9.5,
    reviewCount: 2156,
    features: ["Infinity Edge", "Mediterranean View", "Historic Palace", "Terraced Gardens"],
    description: "Seemingly suspended between sky and sea at an 11th-century palace, this infinity pool offers breathtaking views of the Mediterranean from its perch in the terraced gardens.",
    sources: ["The Luxury Travel Expert", "Travel + Leisure"],
    awards: ["Most Instagrammed Pool in Europe"]
  },
  {
    id: 8,
    rank: 8,
    name: "Lake Pichola Pool",
    hotel: "The Oberoi Udaivilas",
    location: "Udaipur",
    country: "India",
    region: "Asia",
    image: "/images/pool-oberoi-udaivilas.jpg",
    rating: 9.4,
    reviewCount: 4521,
    features: ["Palace Architecture", "Lake View", "88-Foot Pool", "Royal Heritage"],
    description: "An 88-foot architectural wonder overlooking lush gardens and Lake Pichola, set on 50 acres of the 200-year-old hunting grounds of the Maharana of Mewar.",
    sources: ["Condé Nast Traveler", "The Luxury Travel Expert"],
    awards: ["CNT Readers' Choice 2017-2025", "CNT Gold List 2023"]
  },
  {
    id: 9,
    rank: 9,
    name: "Geothermal Lagoon Pool",
    hotel: "The Retreat at Blue Lagoon",
    location: "Grindavik",
    country: "Iceland",
    region: "Europe",
    image: "/images/pool-blue-lagoon-iceland.jpg",
    rating: 9.4,
    reviewCount: 1678,
    features: ["Geothermal", "Private Lagoon", "Spa", "Volcanic Setting"],
    description: "A private, intimate lagoon fed by geothermal seawater from the same wellspring as the famous Blue Lagoon, offering therapeutic bathing without the crowds.",
    sources: ["Condé Nast Traveler"],
    awards: ["CNT Readers' Choice 2019, 2021"]
  },
  {
    id: 10,
    rank: 10,
    name: "Tokyo Skyline Pool",
    hotel: "Aman Tokyo",
    location: "Otemachi, Tokyo",
    country: "Japan",
    region: "Asia",
    image: "/images/pool-aman-tokyo.jpg",
    rating: 9.4,
    reviewCount: 2089,
    features: ["Indoor", "100-Foot Length", "Panoramic Views", "Stone Atrium"],
    description: "A 100-foot heated indoor pool in a vaulted stone atrium high above Tokyo's skyline, part of the renowned Aman Spa with stunning panoramic city views.",
    sources: ["Condé Nast Traveler"],
    awards: ["CNT Gold List 2022", "CNT Readers' Choice 2018-2025"]
  },
  {
    id: 11,
    rank: 11,
    name: "Provence Infinity Pool",
    hotel: "Airelles Gordes, La Bastide",
    location: "Gordes, Provence",
    country: "France",
    region: "Europe",
    image: "/images/pool-11.jpg",
    rating: 9.3,
    reviewCount: 876,
    features: ["100-Foot Length", "Olive Groves", "Mountain View", "Historic Setting"],
    description: "Surrounded by ancient olive trees and dry stone walls, this luxurious 100-foot pool offers sweeping views of neighboring Provençal villages and surrounding mountains.",
    sources: ["Condé Nast Traveler"],
    awards: ["CNT Gold List 2020", "CNT Hot List 2016"]
  },
  {
    id: 12,
    rank: 12,
    name: "Maldives Lagoon Pool",
    hotel: "Huvafen Fushi",
    location: "North Malé Atoll",
    country: "Maldives",
    region: "Asia",
    image: "/images/pool-13.jpg",
    rating: 9.3,
    reviewCount: 1345,
    features: ["Infinity Edge", "Ocean View", "Fiber-Optic Lighting", "Day Beds"],
    description: "A large lagoon-like infinity-edged pool that bleeds into the horizon of the Indian Ocean, surrounded by four-poster day beds and romantically lit with fiber-optic lights at night.",
    sources: ["The Luxury Travel Expert"],
    awards: ["#3 Most Beautiful Pool in the World"]
  },
  {
    id: 13,
    rank: 13,
    name: "Lake Como Floating Pool",
    hotel: "Villa d'Este",
    location: "Cernobbio, Lake Como",
    country: "Italy",
    region: "Europe",
    image: "/images/pool-19.jpg",
    rating: 9.3,
    reviewCount: 2890,
    features: ["Floating Pool", "Lake View", "Historic", "Built-in Jacuzzi"],
    description: "A unique pool floating directly on Lake Como with stunning Alpine views, at a former 16th-century residence of European aristocrats converted into a resort in 1873.",
    sources: ["The Luxury Travel Expert"],
    awards: ["#7 Most Beautiful Pool in the World"]
  },
  {
    id: 14,
    rank: 14,
    name: "Rice Paddy Pools",
    hotel: "Four Seasons Resort Chiang Mai",
    location: "Mae Rim, Chiang Mai",
    country: "Thailand",
    region: "Asia",
    image: "/images/pool-23.jpg",
    rating: 9.2,
    reviewCount: 3456,
    features: ["Infinity Edge", "Rice Terrace View", "Adults Only Option", "Countryside"],
    description: "Two pools that appear to spill over into working rice paddy fields, blurring the lines between luxury and natural beauty in the northern Thailand countryside.",
    sources: ["Condé Nast Traveler"],
    awards: ["CNT Readers' Choice 2017-2025"]
  },
  {
    id: 15,
    rank: 15,
    name: "World's Highest Pool",
    hotel: "Address Beach Resort",
    location: "JBR, Dubai",
    country: "UAE",
    region: "Middle East",
    image: "/images/pool-18.jpg",
    rating: 9.2,
    reviewCount: 4123,
    features: ["Guinness World Record", "77th Floor", "Infinity Edge", "Arabian Gulf View"],
    description: "The world's highest infinity pool at 293.906 meters above ground, 95 meters long, offering panoramic views of the iconic Ain Dubai and Arabian Gulf.",
    sources: ["The Rooftop Guide", "Guinness World Records"],
    awards: ["Guinness World Record - Highest Pool"]
  },
  {
    id: 16,
    rank: 16,
    name: "Copacabana Pool",
    hotel: "Copacabana Palace, A Belmond Hotel",
    location: "Rio de Janeiro",
    country: "Brazil",
    region: "Americas",
    image: "/images/pool-24.jpg",
    rating: 9.2,
    reviewCount: 5678,
    features: ["Art Deco", "Beach Adjacent", "Historic", "Bossa Nova Atmosphere"],
    description: "The pool scene at this South American Grande Dame channels Rio itself - bossa nova beats, happy Cariocas, and a perfect reflection of Copacabana Beach across the street.",
    sources: ["Condé Nast Traveler"],
    awards: ["CNT Gold List 2024", "CNT Readers' Choice 2018-2024"]
  },
  {
    id: 17,
    rank: 17,
    name: "Marrakech Oasis Pool",
    hotel: "Mandarin Oriental Marrakech",
    location: "Marrakech",
    country: "Morocco",
    region: "Africa",
    image: "/images/pool-20.jpg",
    rating: 9.1,
    reviewCount: 2345,
    features: ["Gigantic Pool", "Private Villas", "Decorative Ponds", "Garden Setting"],
    description: "A true oasis 10 minutes from the medina, featuring a gigantic pool flanked by ponds that make it look even more impressive - the jewel of this vast property.",
    sources: ["Condé Nast Traveler"],
    awards: ["CNT Readers' Choice 2017-2025"]
  },
  {
    id: 18,
    rank: 18,
    name: "Turks and Caicos Pool",
    hotel: "Rock House",
    location: "Grace Bay",
    country: "Turks and Caicos",
    region: "Americas",
    image: "/images/pool-34.jpg",
    rating: 9.1,
    reviewCount: 567,
    features: ["Ocean Overlook", "Jagged Rock Formation", "Intimate", "Turquoise Waters"],
    description: "Nestled among jagged rock formations with the bright blue pool as its centerpiece, overlooking the shining turquoise waters that make Turks and Caicos unique.",
    sources: ["Condé Nast Traveler"],
    awards: ["CNT Hot List 2023"]
  },
  {
    id: 19,
    rank: 19,
    name: "Angkor Wat Infinity Pool",
    hotel: "Zannier Hotels Phum Baitang",
    location: "Siem Reap",
    country: "Cambodia",
    region: "Asia",
    image: "/images/pool-19.jpg",
    rating: 9.1,
    reviewCount: 1234,
    features: ["Infinity Edge", "Rice Paddy Setting", "Near UNESCO Site", "Sunset Views"],
    description: "Just a stone's throw from UNESCO World Heritage Site Angkor Wat, surrounded by rice paddy fields and glorious gardens - perfect for catching the sunset.",
    sources: ["Condé Nast Traveler"],
    awards: ["CNT Gold List 2021", "CNT Readers' Choice 2017-2020"]
  },
  {
    id: 20,
    rank: 20,
    name: "Fiji Multi-Level Pool",
    hotel: "COMO Laucala Island",
    location: "Laucala Island",
    country: "Fiji",
    region: "Oceania",
    image: "/images/pool-20.jpg",
    rating: 9.1,
    reviewCount: 456,
    features: ["Private Island", "Multi-Level", "Beach Access", "Many Nooks"],
    description: "A massive multi-layered pool stretching from the pool bar to the beach, with many nooks and crannies for privacy on this exclusive private island resort.",
    sources: ["Condé Nast Traveler"],
    awards: ["CNT Gold List 2018", "CNT Readers' Choice 2019-2025"]
  },
  {
    id: 21,
    rank: 21,
    name: "Brooklyn Bridge View Pool",
    hotel: "1 Hotel Brooklyn Bridge",
    location: "Brooklyn, New York",
    country: "USA",
    region: "Americas",
    image: "/images/pool-22.jpg",
    rating: 9.0,
    reviewCount: 3456,
    features: ["Rooftop", "Manhattan Skyline", "Plunge Pool", "Sustainable Design"],
    description: "A stylish rooftop plunge pool offering exclusive poolside lounging with stunning views over East River and the entire Manhattan skyline.",
    sources: ["Condé Nast Traveler", "The Rooftop Guide"],
    awards: ["CNT Hot List 2018", "CNT Readers' Choice 2018-2023"]
  },
  {
    id: 22,
    rank: 22,
    name: "Serengeti Wildlife Pool",
    hotel: "Four Seasons Safari Lodge Serengeti",
    location: "Serengeti National Park",
    country: "Tanzania",
    region: "Africa",
    image: "/images/pool-21.jpg",
    rating: 9.0,
    reviewCount: 890,
    features: ["Wildlife Watering Hole", "Safari View", "Infinity Edge", "Elevated Platform"],
    description: "A magnificent infinity pool overlooking an animal watering hole where elephants stop for morning drinks, with endless views of the Serengeti plains.",
    sources: ["The Luxury Travel Expert"],
    awards: ["#10 Most Beautiful Pool in the World"]
  },
  {
    id: 23,
    rank: 23,
    name: "Himalayan Golden Pool",
    hotel: "St. Regis Lhasa",
    location: "Lhasa, Tibet",
    country: "China",
    region: "Asia",
    image: "/images/pool-36.jpg",
    rating: 9.0,
    reviewCount: 678,
    features: ["Indoor", "Gold-Lined", "Therapeutic Salt Water", "Mountain View"],
    description: "The spectacular 'Golden Energy Pool' lined with thousands of gold-plated tiles, containing therapeutic salt water heated to 28-32°C, facing the Potala Palace.",
    sources: ["The Luxury Travel Expert"],
    awards: ["#9 Most Beautiful Pool in the World"]
  },
  {
    id: 24,
    rank: 24,
    name: "Costa Rica Volcano Pool",
    hotel: "Nayara Tented Camp",
    location: "La Fortuna",
    country: "Costa Rica",
    region: "Americas",
    image: "/images/pool-31.jpg",
    rating: 9.0,
    reviewCount: 1567,
    features: ["Geothermal", "Volcano View", "Rainforest", "Private Plunge"],
    description: "Private plunge pools fed by geothermal waters flowing from the Arenal Volcano itself, nestled in private rainforest nooks overlooking the soaring volcano.",
    sources: ["Condé Nast Traveler"],
    awards: ["Best Private Pool Experience"]
  },
  {
    id: 25,
    rank: 25,
    name: "Uluru Desert Pool",
    hotel: "Longitude 131°",
    location: "Uluru-Kata Tjuta National Park",
    country: "Australia",
    region: "Oceania",
    image: "/images/pool-32.jpg",
    rating: 8.9,
    reviewCount: 456,
    features: ["Desert Camp", "Uluru View", "Private Plunge", "Luxury Pavilion"],
    description: "Private plunge pools at the Dune Pavilions offering unobstructed views of sacred Uluru, the perfect way to beat the outback heat in profound style.",
    sources: ["Condé Nast Traveler"],
    awards: ["Most Unique Pool Setting"]
  },
  {
    id: 26,
    rank: 26,
    name: "Antigua Beach Pool Villa",
    hotel: "Hermitage Bay",
    location: "St. John's",
    country: "Antigua",
    region: "Americas",
    image: "/images/pool-26.jpg",
    rating: 8.9,
    reviewCount: 789,
    features: ["Beach Pool Villa", "Tropical Gardens", "Hillside Views", "Private"],
    description: "Following an extensive 2025 renovation, Beach Pool Villas now feature private plunge pools enveloped in tropical gardens, with optional hillside ocean views.",
    sources: ["Condé Nast Traveler"],
    awards: ["CNT Gold List 2026"]
  },
  {
    id: 27,
    rank: 27,
    name: "Santorini Cave Pool",
    hotel: "Andronis Boutique Hotel",
    location: "Oia, Santorini",
    country: "Greece",
    region: "Europe",
    image: "/images/pool-27.jpg",
    rating: 8.9,
    reviewCount: 2345,
    features: ["Cave Pool", "Caldera View", "Cliffside", "Private Plunge"],
    description: "Cave pools carved into the rock face offering a chance to literally immerse yourself in the Santorini landscape with sweeping Aegean Sea views.",
    sources: ["Condé Nast Traveler"],
    awards: ["Most Unique Design"]
  },
  {
    id: 28,
    rank: 28,
    name: "Puerto Rico Plantation Pool",
    hotel: "Dorado Beach, A Ritz-Carlton Reserve",
    location: "Dorado",
    country: "Puerto Rico",
    region: "Americas",
    image: "/images/pool-28.jpg",
    rating: 8.9,
    reviewCount: 3456,
    features: ["Historic Estate", "Beachfront", "Private Plunge", "Celebrity History"],
    description: "Private plunge pools at a former Rockefeller plantation where Elizabeth Taylor, Amelia Earhart, and JFK once stayed, offering celebrity-worthy luxury.",
    sources: ["Condé Nast Traveler"],
    awards: ["Most Historic Pool Setting"]
  },
  {
    id: 29,
    rank: 29,
    name: "Camp Sarika Desert Pool",
    hotel: "Amangiri - Camp Sarika",
    location: "Canyon Point, Utah",
    country: "USA",
    region: "Americas",
    image: "/images/pool-29.jpg",
    rating: 8.9,
    reviewCount: 234,
    features: ["Tented Pavilion", "Desert Mesa", "Private Plunge", "Ultra-Exclusive"],
    description: "Ten tented pavilions among the mesas, each with private plunge pools blending naturally into the dramatic desert surroundings - ultimate desert luxury.",
    sources: ["Condé Nast Traveler"],
    awards: ["Most Exclusive Pool Experience"]
  },
  {
    id: 30,
    rank: 30,
    name: "Bangkok Rooftop Pool",
    hotel: "137 Pillars Suites & Residences",
    location: "Sukhumvit, Bangkok",
    country: "Thailand",
    region: "Asia",
    image: "/images/pool-30.jpg",
    rating: 8.8,
    reviewCount: 1890,
    features: ["30th Floor", "360° Views", "Triple Infinity Edge", "Suite Exclusive"],
    description: "An exclusive 30th-floor infinity pool with edges in three directions offering sweeping 360° views over Bangkok - available only to suite guests.",
    sources: ["The Rooftop Guide"],
    awards: ["Best Rooftop Pool in Bangkok"]
  },
  {
    id: 31,
    rank: 31,
    name: "Bali Ayung River Pool",
    hotel: "Mandapa, A Ritz-Carlton Reserve",
    location: "Ubud, Bali",
    country: "Indonesia",
    region: "Asia",
    image: "/images/pool-5.jpg",
    rating: 8.8,
    reviewCount: 2678,
    features: ["River View", "Rainforest", "Rice Paddy View", "Private Villas"],
    description: "25 private-pool villas with views of the surrounding rainforest, rice paddies, or sacred Ayung River, with shallow pools integrating the lush environment.",
    sources: ["Condé Nast Traveler"],
    awards: ["Best River Pool Experience"]
  },
  {
    id: 32,
    rank: 32,
    name: "Mexico Riviera Pool",
    hotel: "Waldorf Astoria Riviera Maya",
    location: "Riviera Maya",
    country: "Mexico",
    region: "Americas",
    image: "/images/pool-3.jpg",
    rating: 8.8,
    reviewCount: 4567,
    features: ["Private Plunge in Every Room", "Beach Access", "Ocean Views", "Cabanas"],
    description: "Every single one of 173 guest rooms features a plunge pool on a private balcony or patio, some with breathtaking ocean views - pool paradise guaranteed.",
    sources: ["Condé Nast Traveler"],
    awards: ["Best All-Room Pool Design"]
  },
  {
    id: 33,
    rank: 33,
    name: "Dominica Clifftop Pool",
    hotel: "Secret Bay",
    location: "Portsmouth",
    country: "Dominica",
    region: "Americas",
    image: "/images/pool-5.jpg",
    rating: 8.8,
    reviewCount: 567,
    features: ["Clifftop", "Rainforest", "Private Villa", "Relais & Châteaux"],
    description: "Dominica's first Relais & Châteaux property, where every villa comes with a private plunge pool high on a clifftop with only the breeze and crashing waves below.",
    sources: ["Condé Nast Traveler"],
    awards: ["Most Secluded Pool Experience"]
  },
  {
    id: 34,
    rank: 34,
    name: "Anguilla Bay Pool Villa",
    hotel: "Belmond Cap Juluca",
    location: "Maundays Bay",
    country: "Anguilla",
    region: "Americas",
    image: "/images/pool-35.jpg",
    rating: 8.7,
    reviewCount: 1234,
    features: ["Beachfront", "Private Plunge", "Caribbean View", "White Sand"],
    description: "Beachfront Pool Villas with private plunge pools just steps from the crystal-clear waters of Maundays Bay - ultimate Caribbean luxury.",
    sources: ["Condé Nast Traveler"],
    awards: ["Best Caribbean Pool Villa"]
  },
  {
    id: 35,
    rank: 35,
    name: "Namibia Desert Lodge Pool",
    hotel: "andBeyond Sossusvlei Desert Lodge",
    location: "Sossusvlei",
    country: "Namibia",
    region: "Africa",
    image: "/images/pool-33.jpg",
    rating: 8.7,
    reviewCount: 345,
    features: ["Desert Luxury", "Private Veranda", "Chilled Plunge", "Stargazing"],
    description: "Chilled plunge pools to beat the desert heat, with secret butler hatches and in-room ice cream stocked freezers - the ultimate Namibian desert oasis.",
    sources: ["Condé Nast Traveler"],
    awards: ["Best Desert Pool Experience"]
  },
  {
    id: 36,
    rank: 36,
    name: "Botswana Safari Camp Pool",
    hotel: "Jack's Camp",
    location: "Makgadikgadi Salt Pans",
    country: "Botswana",
    region: "Africa",
    image: "/images/pool-4.jpg",
    rating: 8.7,
    reviewCount: 234,
    features: ["1940s Style", "Salt Pans View", "Safari Camp", "Private Plunge"],
    description: "Part flashback, part mirage - a beloved safari camp with 1940s style that added private plunge pools in 2020, overlooking the otherworldly salt pans.",
    sources: ["Condé Nast Traveler"],
    awards: ["Most Unique Safari Pool"]
  },
  {
    id: 37,
    rank: 37,
    name: "Rome Hilltop Pool",
    hotel: "Rome Cavalieri, A Waldorf Astoria Hotel",
    location: "Monte Mario, Rome",
    country: "Italy",
    region: "Europe",
    image: "/images/pool-6.jpg",
    rating: 8.7,
    reviewCount: 5678,
    features: ["Hilltop", "Rome Skyline", "Private Hot Tub", "Night Sky View"],
    description: "Private plunge hot tubs in the Planetarium and Presidential Suites offering romantic views over the Eternal City from a hilltop perch.",
    sources: ["Condé Nast Traveler"],
    awards: ["Best City View Pool"]
  },
  {
    id: 38,
    rank: 38,
    name: "Cape Town Framed Pool",
    hotel: "The Silo Hotel",
    location: "V&A Waterfront, Cape Town",
    country: "South Africa",
    region: "Africa",
    image: "/images/pool-2.jpg",
    rating: 8.7,
    reviewCount: 1567,
    features: ["Architectural Gem", "Harbor View", "Mountain View", "Brick Windows"],
    description: "An 11th-floor infinity pool framed by open 'brick-windows' opening to panoramic views over the city, harbor, ocean and Table Mountain.",
    sources: ["The Rooftop Guide"],
    awards: ["Most Architecturally Stunning Pool"]
  },
  {
    id: 39,
    rank: 39,
    name: "London Shard Pool",
    hotel: "Shangri-La at The Shard",
    location: "London",
    country: "UK",
    region: "Europe",
    image: "/images/pool-2.jpg",
    rating: 8.6,
    reviewCount: 4567,
    features: ["52nd Floor", "City Skyline", "Western Europe's Highest", "Indoor"],
    description: "Western Europe's highest hotel swimming pool on the 52nd floor, offering unparalleled views of the London skyline from The Shard.",
    sources: ["The Rooftop Guide"],
    awards: ["Highest Pool in Western Europe"]
  },
  {
    id: 40,
    rank: 40,
    name: "Hong Kong Sky Pool",
    hotel: "W Hong Kong",
    location: "West Kowloon",
    country: "Hong Kong",
    region: "Asia",
    image: "/images/pool-2.jpg",
    rating: 8.6,
    reviewCount: 3456,
    features: ["76th Floor", "Harbor View", "One of World's Highest", "Infinity Edge"],
    description: "One of the highest outdoor swimming pools globally, located on the 76th floor with stunning Victoria Harbour views.",
    sources: ["The Rooftop Guide"],
    awards: ["One of World's Highest Pools"]
  },
  {
    id: 41,
    rank: 41,
    name: "Lake Como Infinity Pool",
    hotel: "Hilton Lake Como",
    location: "Como",
    country: "Italy",
    region: "Europe",
    image: "/images/pool-6.jpg",
    rating: 8.6,
    reviewCount: 2890,
    features: ["Rooftop", "Lake View", "Year-Round Heated", "Panoramic"],
    description: "The Terrazza 241 rooftop infinity pool overlooks breathtaking Lake Como and town views, heated year-round with glamorous lounging areas.",
    sources: ["The Rooftop Guide"],
    awards: ["Best Lake View Pool"]
  },
  {
    id: 42,
    rank: 42,
    name: "Pattaya Sky Pool",
    hotel: "Siam@Siam Design Hotel Pattaya",
    location: "Pattaya",
    country: "Thailand",
    region: "Asia",
    image: "/images/pool-2.jpg",
    rating: 8.5,
    reviewCount: 2345,
    features: ["27th Floor", "Highest in Pattaya", "Bay View", "Colorful Design"],
    description: "The highest infinity pool in Pattaya on the 27th floor, surrounded with sweeping views of Pattaya Bay and a vibrant, artistic atmosphere.",
    sources: ["The Rooftop Guide"],
    awards: ["Highest Pool in Pattaya"]
  },
  {
    id: 43,
    rank: 43,
    name: "Ibiza Harbor Pool",
    hotel: "Aguas de Ibiza Grand Luxe Hotel",
    location: "Santa Eulalia del Río",
    country: "Spain",
    region: "Europe",
    image: "/images/pool-1.jpg",
    rating: 8.5,
    reviewCount: 1678,
    features: ["Eco-Friendly", "Harbor View", "Rooftop", "Mediterranean"],
    description: "An amazing rooftop infinity pool at an innovative eco-friendly hotel, overlooking one of Ibiza's busiest harbors and the Mediterranean.",
    sources: ["The Rooftop Guide"],
    awards: ["Best Eco-Luxury Pool"]
  },
  {
    id: 44,
    rank: 44,
    name: "Lake Garda Floating Pool",
    hotel: "AH Porticcioli",
    location: "San Felice del Benaco",
    country: "Italy",
    region: "Europe",
    image: "/images/pool-6.jpg",
    rating: 8.5,
    reviewCount: 456,
    features: ["Lake View", "Heated", "Jacuzzi", "Sunset Aperitivo"],
    description: "A heated rooftop infinity pool that feels like floating on Lake Garda, with panoramic views of the Gulf of Salò and 6 jacuzzi areas.",
    sources: ["The Rooftop Guide"],
    awards: ["Best Lake View Boutique Pool"]
  },
  {
    id: 45,
    rank: 45,
    name: "Virginia Beach Oceanfront Pool",
    hotel: "Hilton Virginia Beach Oceanfront",
    location: "Virginia Beach",
    country: "USA",
    region: "Americas",
    image: "/images/pool-3.jpg",
    rating: 8.4,
    reviewCount: 3456,
    features: ["21st Floor", "Atlantic Ocean View", "Indoor & Outdoor", "Igloo Lounge"],
    description: "A 21st-floor rooftop infinity pool with panoramic Atlantic Ocean views, featuring both indoor and outdoor pools plus a winter Igloo Lounge.",
    sources: ["The Rooftop Guide"],
    awards: ["Best Beach View Pool"]
  },
  {
    id: 46,
    rank: 46,
    name: "Cabo Rooftop Pool",
    hotel: "Corazón Cabo Resort & Spa",
    location: "Cabo San Lucas",
    country: "Mexico",
    region: "Americas",
    image: "/images/pool-3.jpg",
    rating: 8.4,
    reviewCount: 2345,
    features: ["9th Floor", "Ocean View", "360° Views", "Beach Adjacent"],
    description: "The Rooftop 360 Infinity Pool offers the best views in Cabo, where it's hard to tell where the pool ends and the ocean begins.",
    sources: ["The Rooftop Guide"],
    awards: ["Best Cabo Pool"]
  },
  {
    id: 47,
    rank: 47,
    name: "Vienna Rooftop Pool",
    hotel: "Grand Ferdinand",
    location: "Vienna",
    country: "Austria",
    region: "Europe",
    image: "/images/pool-2.jpg",
    rating: 8.4,
    reviewCount: 1890,
    features: ["Rooftop", "Year-Round", "City View", "Riviera-Inspired"],
    description: "A glittering rooftop pool heated to 23°C and available year-round, with spectacular views over the Vienna rooftops and Riviera-inspired dining.",
    sources: ["The Rooftop Guide"],
    awards: ["Best City Center Pool"]
  },
  {
    id: 48,
    rank: 48,
    name: "St. Louis Historic Pool",
    hotel: "The Last Hotel",
    location: "Washington Ave, St. Louis",
    country: "USA",
    region: "Americas",
    image: "/images/pool-2.jpg",
    rating: 8.3,
    reviewCount: 1234,
    features: ["Historic Building", "Heated", "11th Floor", "Skyline View"],
    description: "A heated rooftop pool in the iconic 1909 International Shoe Company building, 11 floors above Washington Ave with St. Louis skyline views.",
    sources: ["The Rooftop Guide"],
    awards: ["Best Historic Rooftop Pool"]
  },
  {
    id: 49,
    rank: 49,
    name: "Tucson Desert Pool",
    hotel: "Graduate Tucson",
    location: "Tucson, Arizona",
    country: "USA",
    region: "Americas",
    image: "/images/pool-4.jpg",
    rating: 8.3,
    reviewCount: 987,
    features: ["Desert View", "Mountain View", "Retro-Chic", "Stadium View"],
    description: "A beautiful rooftop pool with panoramic views of Mt. Lemmon and Arizona Stadium, perfect for enjoying Tucson's 300+ days of sunshine.",
    sources: ["The Rooftop Guide"],
    awards: ["Best University District Pool"]
  },
  {
    id: 50,
    rank: 50,
    name: "Ubud Jungle Pool",
    hotel: "Bisma Eight",
    location: "Ubud, Bali",
    country: "Indonesia",
    region: "Asia",
    image: "/images/pool-5.jpg",
    rating: 8.3,
    reviewCount: 2345,
    features: ["Rooftop", "Jungle View", "Infinity Edge", "Heated Evening"],
    description: "An 18-meter infinity rooftop pool overlooking the Ubud wilderness, with heated water during cooler evenings for year-round swimming.",
    sources: ["The Rooftop Guide"],
    awards: ["Best Jungle Rooftop Pool"]
  },
  {
    id: 51,
    rank: 51,
    name: "Grand Hotel Tremezzo Floating Pool",
    hotel: "Grand Hotel Tremezzo",
    location: "Lake Como",
    country: "Italy",
    region: "Europe",
    image: "/images/pool-19.jpg",
    rating: 9.3,
    reviewCount: 3456,
    features: ["Floating Pool", "Lake View", "Art Nouveau", "Historic"],
    description: "A floating pool sitting directly on Lake Como with views of Bellagio, featuring a Lido-like beachfront with bright orange and white umbrellas at this Liberty-style 1910 palazzo.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice", "Most Cinematic Pool"]
  },
  {
    id: 52,
    rank: 52,
    name: "Daios Cove Private Pool Villas",
    hotel: "Daios Cove Luxury Resort",
    location: "Agios Nikolaos, Crete",
    country: "Greece",
    region: "Europe",
    image: "/images/pool-1.jpg",
    rating: 9.2,
    reviewCount: 2890,
    features: ["Private Villa Pool", "Sea View", "Secluded", "Couples Retreat"],
    description: "Private pools in villas and suites facing the glittering, crystal-clear Aegean Sea, where couples can lounge for hours without seeing another soul.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice"]
  },
  {
    id: 53,
    rank: 53,
    name: "Amanruya Pool",
    hotel: "Amanruya",
    location: "Bodrum",
    country: "Turkey",
    region: "Europe",
    image: "/images/pool-1.jpg",
    rating: 9.4,
    reviewCount: 1234,
    features: ["Palatial", "Private Pool Suites", "Aegean Coast", "Ultra-Luxury"],
    description: "Jaw-dropping palatial property on Bodrum's glitzy Göltürkbükü coastline with gargantuan shared pools and private sanctuaries in sumptuous pool suites.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice"]
  },
  {
    id: 54,
    rank: 54,
    name: "Castello di Vicarello Pool",
    hotel: "Castello di Vicarello",
    location: "Tuscany",
    country: "Italy",
    region: "Europe",
    image: "/images/pool-7.jpg",
    rating: 9.1,
    reviewCount: 456,
    features: ["Hilltop Castle", "Tuscan Views", "Heated", "Boutique"],
    description: "Perfectly perched hilltop castle with chic swimming pools offering spectacular rolling Tuscan hill views at this renovated family-run property.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice"]
  },
  {
    id: 55,
    rank: 55,
    name: "The Bodrum Edition Pool",
    hotel: "The Bodrum Edition",
    location: "Bodrum",
    country: "Turkey",
    region: "Europe",
    image: "/images/pool-1.jpg",
    rating: 9.0,
    reviewCount: 2345,
    features: ["White Sand Beach", "Sunset Views", "Bay Views", "Trendy"],
    description: "One of the coolest hideouts on Turkey's most in-demand peninsula with a huge swimming pool perfect for sunset appreciation as the bay lights twinkle.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice"]
  },
  {
    id: 56,
    rank: 56,
    name: "Nobu Hotel Ibiza Bay Pool",
    hotel: "Nobu Hotel Ibiza Bay",
    location: "Talamanca Bay, Ibiza",
    country: "Spain",
    region: "Europe",
    image: "/images/pool-25.jpg",
    rating: 9.0,
    reviewCount: 3456,
    features: ["Beachfront", "DJ Sets", "Slim Aarons Aesthetic", "Rosé Culture"],
    description: "The pool deck hub where mellow music accompanies a constant tinkle of ice in glasses and methuselahs of rosé - Slim Aarons-esque country club aesthetic.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice", "Best Party Pool"]
  },
  {
    id: 57,
    rank: 57,
    name: "Alila Ubud Infinity Pool",
    hotel: "Alila Ubud",
    location: "Ubud, Bali",
    country: "Indonesia",
    region: "Asia",
    image: "/images/pool-15.jpg",
    rating: 9.1,
    reviewCount: 4567,
    features: ["Infinity Edge", "Ayung River Valley", "Jungle View", "Iconic"],
    description: "The iconic infinity pool that almost blends into the landscape of the lush Ayung River valley, featured in countless travel publications.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice", "Most Photographed Pool"]
  },
  {
    id: 58,
    rank: 58,
    name: "Castello di Reschio Infinity Pool",
    hotel: "Castello di Reschio",
    location: "Umbria",
    country: "Italy",
    region: "Europe",
    image: "/images/pool-7.jpg",
    rating: 9.2,
    reviewCount: 678,
    features: ["Hillside Views", "Landscaped Gardens", "Private Estate", "Romantic"],
    description: "Umbria's hillside unravels beneath the infinity pool at this reinvented farmhouse estate with landscaped gardens of rosemary, lavender, olive and pomegranate trees.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice"]
  },
  {
    id: 59,
    rank: 59,
    name: "The Dolli Rooftop Pool",
    hotel: "The Dolli at Athens",
    location: "Athens",
    country: "Greece",
    region: "Europe",
    image: "/images/pool-1.jpg",
    rating: 8.9,
    reviewCount: 1234,
    features: ["Parthenon Views", "Rooftop", "Historic Mansion", "Infinity Edge"],
    description: "The infinity pool creates the illusion of floating in the Parthenon at this reimagined 1925 shipping magnate mansion turned luxury hotel.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice", "Best Historic View Pool"]
  },
  {
    id: 60,
    rank: 60,
    name: "Soho Warehouse Rooftop Pool",
    hotel: "Soho Warehouse",
    location: "Downtown Los Angeles",
    country: "USA",
    region: "Americas",
    image: "/images/pool-22.jpg",
    rating: 8.8,
    reviewCount: 2345,
    features: ["Rooftop", "Mountain Views", "Members Club", "Industrial Chic"],
    description: "A sunny rooftop paradise with unreal views of Los Angeles and the mountains beyond, featuring plush cabanas with baby-blue coolers at the largest Soho House in the US.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice"]
  },
  {
    id: 61,
    rank: 61,
    name: "Cali Mykonos Pool",
    hotel: "Cali Mykonos",
    location: "Kalafati Beach, Mykonos",
    country: "Greece",
    region: "Europe",
    image: "/images/pool-1.jpg",
    rating: 8.9,
    reviewCount: 1567,
    features: ["Olympic Size", "Private Beach", "Secluded", "Curvaceous Design"],
    description: "Hidden on a craggy fortress on secluded Kalafati beach, worlds away from Mykonos Old Town with a sexy curvaceous pool of epic Olympic proportion.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice"]
  },
  {
    id: 62,
    rank: 62,
    name: "Cap Rocat Plunge Pools",
    hotel: "Cap Rocat",
    location: "Bay of Palma, Mallorca",
    country: "Spain",
    region: "Europe",
    image: "/images/pool-25.jpg",
    rating: 9.1,
    reviewCount: 1890,
    features: ["Military Fort", "Cliffside", "Private Plunge", "Historic"],
    description: "A former military fort on spectacular cliffs overlooking the Bay of Palma, with lookout points converted into rooms with private plunge pools.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice", "Most Unique Historic Pool"]
  },
  {
    id: 63,
    rank: 63,
    name: "25hours Hotel Dubai Rooftop Pool",
    hotel: "25hours Hotel One Central",
    location: "Dubai",
    country: "UAE",
    region: "Middle East",
    image: "/images/pool-18.jpg",
    rating: 8.7,
    reviewCount: 2345,
    features: ["Museum Views", "Creative Hub", "Rooftop Bar", "Un-Dubai Vibe"],
    description: "Forget glitz and glam - this cool un-Dubai hotel rooftop pool overlooks the Museum of the Future which lights up spectacularly in the evening.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice", "Best Alternative Dubai Pool"]
  },
  {
    id: 64,
    rank: 64,
    name: "Singita Sweni Lodge Pool",
    hotel: "Singita Sweni Lodge",
    location: "Kruger National Park",
    country: "South Africa",
    region: "Africa",
    image: "/images/pool-21.jpg",
    rating: 9.3,
    reviewCount: 456,
    features: ["Safari", "Private Infinity", "River View", "Design-Forward"],
    description: "Intimate, colorful and explicitly African lodge with private infinity pools close to the river, feeling like a jungle hideaway of a design-aware billionaire.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice", "Best Safari Pool"]
  },
  {
    id: 65,
    rank: 65,
    name: "Hotel Santa Caterina Pool",
    hotel: "Hotel Santa Caterina",
    location: "Amalfi",
    country: "Italy",
    region: "Europe",
    image: "/images/pool-6.jpg",
    rating: 9.0,
    reviewCount: 2345,
    features: ["Cliffside", "Glass Elevator", "Slim Aarons", "Grande Dame"],
    description: "A grande dame clinging to limestone rocks over six storeys, reached by a staggering glass-fronted lift through terraced gardens to a seaside pool straight out of Slim Aarons.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice"]
  },
  {
    id: 66,
    rank: 66,
    name: "Chapung SeBali Jungle Pool",
    hotel: "Chapung SeBali Resort and Spa",
    location: "Ubud, Bali",
    country: "Indonesia",
    region: "Asia",
    image: "/images/pool-15.jpg",
    rating: 8.8,
    reviewCount: 1234,
    features: ["Rice Terraces", "Jungle Sounds", "Infinity Edge", "Dragonflies"],
    description: "Infinity pool overlooking vivid green rice terraces and lush rainforest, with geckos croaking, the Osh river running below, and dragonflies dipping in and out of the water.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice"]
  },
  {
    id: 67,
    rank: 67,
    name: "Capella Ubud Saltwater Pools",
    hotel: "Capella Ubud",
    location: "Keliki Valley, Bali",
    country: "Indonesia",
    region: "Asia",
    image: "/images/pool-15.jpg",
    rating: 9.2,
    reviewCount: 1890,
    features: ["Saltwater", "Bill Bensley Design", "Jungle Tents", "Whimsical"],
    description: "Deep in the higgledy-piggledy Keliki Valley, designer Bill Bensley's imaginative playground features private saltwater pools scattered among lush jungle grounds.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice", "Best Designer Pool"]
  },
  {
    id: 68,
    rank: 68,
    name: "Six Senses Zil Pasyon Pool",
    hotel: "Six Senses Zil Pasyon",
    location: "Félicité Island",
    country: "Seychelles",
    region: "Africa",
    image: "/images/pool-27.jpg",
    rating: 9.3,
    reviewCount: 678,
    features: ["Private Island", "Tree Villas", "Rewilded Nature", "Dramatic"],
    description: "One of the finest private islands in the Indian Ocean with villas up in the trees or secluded amid rocks, the closest thing to super-smart minimalist tree-houses.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice", "Best Private Island Pool"]
  },
  {
    id: 69,
    rank: 69,
    name: "Wild Coast Tented Lodge Pool",
    hotel: "Wild Coast Tented Lodge",
    location: "Yala National Park",
    country: "Sri Lanka",
    region: "Asia",
    image: "/images/pool-21.jpg",
    rating: 9.0,
    reviewCount: 567,
    features: ["Scallop-Edged", "Leopard Territory", "Beach Adjacent", "Eco-Luxury"],
    description: "Scallop-edged infinity pool in untapped wilderness where leopards slink at night and elephants thunder by day, with surf pounding the nearby beach.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice", "Best Wildlife Pool"]
  },
  {
    id: 70,
    rank: 70,
    name: "Qualia Pool",
    hotel: "Qualia",
    location: "Hamilton Island",
    country: "Australia",
    region: "Oceania",
    image: "/images/pool-29.jpg",
    rating: 9.4,
    reviewCount: 2345,
    features: ["Great Barrier Reef", "Peninsula Setting", "Ultra-Luxury", "Private Beach"],
    description: "Super-smart Qualia sits on its own peninsula in the Great Barrier Reef with stunning pools overlooking the Whitsunday Islands.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice", "Best Reef Pool"]
  },
  {
    id: 71,
    rank: 71,
    name: "The Berkeley Rooftop Pool",
    hotel: "The Berkeley",
    location: "Knightsbridge, London",
    country: "UK",
    region: "Europe",
    image: "/images/pool-28.jpg",
    rating: 9.1,
    reviewCount: 3456,
    features: ["Retractable Roof", "Gold Mosaic", "Year-Round", "Knightsbridge Views"],
    description: "The rooftop pool tiled in iridescent white and gold mosaic is a welcome oasis from Knightsbridge, with a sliding roof for all-weather swimming.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice", "Best London Pool"]
  },
  {
    id: 72,
    rank: 72,
    name: "Six Senses Yao Noi Pool",
    hotel: "Six Senses Yao Noi",
    location: "Phang Nga Bay",
    country: "Thailand",
    region: "Asia",
    image: "/images/pool-23.jpg",
    rating: 9.2,
    reviewCount: 2890,
    features: ["James Bond Bay", "Limestone Karsts", "Andaman Sea", "Panoramic"],
    description: "Looking out over Thailand's James Bond-worthy Phang Nga Bay with incredible views of the limestone formations jutting out of the Andaman Sea.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice", "Best Scenic Pool"]
  },
  {
    id: 73,
    rank: 73,
    name: "Le Bristol Paris Rooftop Pool",
    hotel: "Le Bristol Paris",
    location: "Paris",
    country: "France",
    region: "Europe",
    image: "/images/pool-28.jpg",
    rating: 9.3,
    reviewCount: 2345,
    features: ["6th Floor", "Rooftop Views", "Sun Deck", "Palace Hotel"],
    description: "The rooftop pool on the sixth floor opens onto a vast sun deck offering unrivalled views across the Paris rooftops at this legendary palace hotel.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice", "Best Paris Pool"]
  },
  {
    id: 74,
    rank: 74,
    name: "Alila Villas Uluwatu Pool",
    hotel: "Alila Villas Uluwatu",
    location: "Uluwatu, Bali",
    country: "Indonesia",
    region: "Asia",
    image: "/images/pool-15.jpg",
    rating: 9.3,
    reviewCount: 3456,
    features: ["50m Clifftop", "Ocean Views", "Infinity Edge", "Dramatic"],
    description: "The 50-meter-high clifftop infinity pool with views out over the Indian Ocean on Bali's spectacular southernmost tip.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice", "Best Clifftop Pool"]
  },
  {
    id: 75,
    rank: 75,
    name: "Il Sereno Lake Como Pool",
    hotel: "Il Sereno",
    location: "Lake Como",
    country: "Italy",
    region: "Europe",
    image: "/images/pool-19.jpg",
    rating: 9.2,
    reviewCount: 1890,
    features: ["Patricia Urquiola Design", "Heated", "Alpine Views", "Contemporary"],
    description: "Designer Patricia Urquiola placed pea-green sun loungers around the heated pool with views of the Italian Alps and Lake Como.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice", "Best Designer Pool"]
  },
  {
    id: 76,
    rank: 76,
    name: "Chedi Muscat Pools",
    hotel: "The Chedi Muscat",
    location: "Muscat",
    country: "Oman",
    region: "Middle East",
    image: "/images/pool-20.jpg",
    rating: 9.1,
    reviewCount: 4567,
    features: ["21-Acre Oasis", "Three Pools", "Desert Setting", "Temperature-Controlled"],
    description: "Set in the desert of Oman with a 21-acre oasis garden complete with three temperature-controlled swimming pools.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice", "Best Desert Oasis Pool"]
  },
  {
    id: 77,
    rank: 77,
    name: "Four Seasons Koh Samui Plunge Pools",
    hotel: "Four Seasons Resort Koh Samui",
    location: "Koh Samui",
    country: "Thailand",
    region: "Asia",
    image: "/images/pool-23.jpg",
    rating: 9.2,
    reviewCount: 3456,
    features: ["Gulf Views", "Villa Plunge Pools", "Wine Fridge", "Private Decks"],
    description: "Villas with expansive Gulf of Thailand views, decks with big plunge pools, shaded daybeds, and stocked wine fridges.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice"]
  },
  {
    id: 78,
    rank: 78,
    name: "Amanpuri Phuket Pool",
    hotel: "Amanpuri",
    location: "Phuket",
    country: "Thailand",
    region: "Asia",
    image: "/images/pool-23.jpg",
    rating: 9.4,
    reviewCount: 2890,
    features: ["Classic Thai", "Andaman Sea", "A-List Hideout", "Private Pavilions"],
    description: "Guests get a sophisticated, A-list retune in a classic Thai setting at this legendary Aman resort on Phuket's coast.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice", "Most Legendary Pool"]
  },
  {
    id: 79,
    rank: 79,
    name: "Four Seasons Nam Hai Triple Pools",
    hotel: "Four Seasons The Nam Hai",
    location: "Hoi An",
    country: "Vietnam",
    region: "Asia",
    image: "/images/pool-23.jpg",
    rating: 9.1,
    reviewCount: 2345,
    features: ["Three Tiered Pools", "Palm Trees", "Beach Access", "Mindful Spa"],
    description: "At this mindful spa resort, three tiered swimming pools cascade under swaying palms near the pristine Vietnamese beach.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice"]
  },
  {
    id: 80,
    rank: 80,
    name: "Fregate Island Pool",
    hotel: "Fregate Island Private",
    location: "Fregate Island",
    country: "Seychelles",
    region: "Africa",
    image: "/images/pool-27.jpg",
    rating: 9.5,
    reviewCount: 345,
    features: ["Private Island", "Giant Tortoises", "Conservation", "Ultra-Exclusive"],
    description: "Ultra-exclusive private island in the Seychelles with stunning infinity pools overlooking pristine beaches and home to giant Aldabra tortoises.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice", "Most Exclusive Pool"]
  },
  {
    id: 81,
    rank: 81,
    name: "Joali Maldives Pool",
    hotel: "Joali",
    location: "Raa Atoll",
    country: "Maldives",
    region: "Asia",
    image: "/images/pool-16.jpg",
    rating: 9.3,
    reviewCount: 1234,
    features: ["Lagoon Blend", "Barefoot Luxury", "Art Collection", "Hybrid Design"],
    description: "Sink into an infinity pool that blends into the surrounding lagoon at this deep-rooted, solid luxury Maldives hybrid resort.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice"]
  },
  {
    id: 82,
    rank: 82,
    name: "Alila Kothaifaru Pool",
    hotel: "Alila Kothaifaru Maldives",
    location: "Raa Atoll",
    country: "Maldives",
    region: "Asia",
    image: "/images/pool-16.jpg",
    rating: 9.2,
    reviewCount: 890,
    features: ["Natural Island", "Pool Villas", "Charming Staff", "Pristine"],
    description: "Situated on a lush, natural private island with pool villas and wonderfully friendly staff, easily one of the most charming hotels in the Maldives.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice"]
  },
  {
    id: 83,
    rank: 83,
    name: "Borgo Pignano Quarry Pool",
    hotel: "Borgo Pignano",
    location: "Tuscany",
    country: "Italy",
    region: "Europe",
    image: "/images/pool-7.jpg",
    rating: 9.0,
    reviewCount: 567,
    features: ["Ancient Quarry", "Olive Groves", "Vineyard Views", "Historic"],
    description: "Infinity pool carved from an ancient limestone quarry overlooking stretches of olive groves, vineyards, fields and Tuscan woods.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice", "Most Unique Setting"]
  },
  {
    id: 84,
    rank: 84,
    name: "Erosantorini Tiered Pool",
    hotel: "Erosantorini",
    location: "Oia, Santorini",
    country: "Greece",
    region: "Europe",
    image: "/images/pool-1.jpg",
    rating: 9.1,
    reviewCount: 678,
    features: ["Tiered Terraces", "Sunset Views", "Aegean Sea", "Boutique"],
    description: "The tiered pool terrace where the main event is watching the sun slip into the Aegean, at this intimate Santorini boutique hotel.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice", "Best Sunset Pool"]
  },
  {
    id: 85,
    rank: 85,
    name: "Villa Althea Suspended Pool",
    hotel: "Villa Althea",
    location: "Kefalonia",
    country: "Greece",
    region: "Europe",
    image: "/images/pool-1.jpg",
    rating: 9.2,
    reviewCount: 234,
    features: ["Suspended 300m", "Myrtos Beach View", "Private Villa", "Dramatic"],
    description: "Take the plunge at Villa Althea and find yourself suspended 300 metres above the famous Myrtos beach.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice", "Most Dramatic Pool"]
  },
  {
    id: 86,
    rank: 86,
    name: "Tierra Atacama Volcano View Pool",
    hotel: "Tierra Atacama",
    location: "San Pedro de Atacama",
    country: "Chile",
    region: "Americas",
    image: "/images/pool-33.jpg",
    rating: 9.0,
    reviewCount: 1234,
    features: ["Volcano Views", "Desert Setting", "Stargazing", "Spa"],
    description: "The pool at the Uma Spa looks out onto the smoking Licancabur Volcano and Chile's otherworldly Atacama Desert landscape.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice", "Best Volcano View Pool"]
  },
  {
    id: 87,
    rank: 87,
    name: "Omaanda Infinity Pool",
    hotel: "Omaanda by Zannier Hotels",
    location: "Namibia Savannah",
    country: "Namibia",
    region: "Africa",
    image: "/images/pool-33.jpg",
    rating: 9.1,
    reviewCount: 456,
    features: ["Savannah Views", "Mountain Vista", "Safari Lodge", "Infinity Edge"],
    description: "At smart lodge Omaanda, the infinity pool looks out over Namibia's stark, dramatic mountainscape from the savannah.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice"]
  },
  {
    id: 88,
    rank: 88,
    name: "Miramonti Boutique Pool",
    hotel: "Miramonti Boutique Hotel",
    location: "Merano, Dolomites",
    country: "Italy",
    region: "Europe",
    image: "/images/pool-30.jpg",
    rating: 9.0,
    reviewCount: 1890,
    features: ["Alpine Valley", "Dolomites Views", "Scandi Design", "Spa Retreat"],
    description: "An Alpine spa retreat with jaw-dropping valley views in the Dolomites, more clean-cut Scandi than traditional chalet with one of the prettiest pools in the region.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice", "Best Alpine Pool"]
  },
  {
    id: 89,
    rank: 89,
    name: "Hotel Oderberger Historic Pool",
    hotel: "Hotel Oderberger",
    location: "Berlin",
    country: "Germany",
    region: "Europe",
    image: "/images/pool-28.jpg",
    rating: 8.9,
    reviewCount: 2345,
    features: ["1898 Bathhouse", "Vaulted Ceiling", "Historic", "65ft Indoor"],
    description: "Pergamon Museum architect Ludwig Hoffmann designed this palatial 1898 public bathhouse, now featuring a grand 65ft heated indoor pool beneath a towering vaulted ceiling.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice", "Best Historic Indoor Pool"]
  },
  {
    id: 90,
    rank: 90,
    name: "Manon Les Suites Tropical Pool",
    hotel: "Manon Les Suites",
    location: "Copenhagen",
    country: "Denmark",
    region: "Europe",
    image: "/images/pool-28.jpg",
    rating: 8.8,
    reviewCount: 1567,
    features: ["Indoor Tropical", "Former Factory", "Riad Style", "Jungle Courtyard"],
    description: "A former factory reconfigured in funky riad style with an indoor pool lined with day beds and surrounded by greenery like a wonderfully steamy tropical wonderland.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice", "Best Urban Oasis Pool"]
  },
  {
    id: 91,
    rank: 91,
    name: "Sun Gardens Dubrovnik Circular Pool",
    hotel: "Sun Gardens Dubrovnik",
    location: "Dubrovnik",
    country: "Croatia",
    region: "Europe",
    image: "/images/pool-25.jpg",
    rating: 8.8,
    reviewCount: 3456,
    features: ["Circular Design", "Adriatic Sea", "Curves into Ocean", "Resort"],
    description: "The stunning circular pool curves out into the crystal-clear Adriatic Sea at this Dubrovnik resort.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice"]
  },
  {
    id: 92,
    rank: 92,
    name: "One&Only Reethi Rah Spa Pool",
    hotel: "One&Only Reethi Rah",
    location: "North Malé Atoll",
    country: "Maldives",
    region: "Asia",
    image: "/images/pool-16.jpg",
    rating: 9.3,
    reviewCount: 2345,
    features: ["Pool-in-Pool-in-Sea", "ESPA Spa", "Overwater", "Multi-Level"],
    description: "A pool-within-a-pool-within-the-sea at The Spa by ESPA, creating a mesmerizing multi-level aquatic experience.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice", "Most Innovative Pool Design"]
  },
  {
    id: 93,
    rank: 93,
    name: "Amansara Pool",
    hotel: "Amansara",
    location: "Siem Reap",
    country: "Cambodia",
    region: "Asia",
    image: "/images/pool-23.jpg",
    rating: 9.2,
    reviewCount: 890,
    features: ["King's Guesthouse", "Historic", "Minimalist", "Temple Base"],
    description: "This minimalist hotel in a former guesthouse of King Sihanouk has hosted President Charles de Gaulle and Jacqueline Kennedy.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice", "Most Historic Celebrity Pool"]
  },
  {
    id: 94,
    rank: 94,
    name: "Chiva Som Ocean Pool",
    hotel: "Chiva Som",
    location: "Hua Hin",
    country: "Thailand",
    region: "Asia",
    image: "/images/pool-23.jpg",
    rating: 9.4,
    reviewCount: 1234,
    features: ["Grand Dame Spa", "Ocean Views", "Wellness Pioneer", "Therapeutic"],
    description: "The undisputed grand dame of destination spas overlooks the Gulf of Thailand with legendary wellness programs.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice", "Best Wellness Pool"]
  },
  {
    id: 95,
    rank: 95,
    name: "Phum Baitang Rice Paddy Pool",
    hotel: "Phum Baitang",
    location: "Siem Reap",
    country: "Cambodia",
    region: "Asia",
    image: "/images/pool-23.jpg",
    rating: 9.0,
    reviewCount: 1567,
    features: ["Rice Paddies", "Fresh Water", "Stilt Houses", "Authentic"],
    description: "The huge fresh-water swimming pool is surrounded by working paddy fields in a traditional Cambodian village setting.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice"]
  },
  {
    id: 96,
    rank: 96,
    name: "La Reserve Beaulieu Pool",
    hotel: "La Reserve de Beaulieu",
    location: "Beaulieu-sur-Mer",
    country: "France",
    region: "Europe",
    image: "/images/pool-5.jpg",
    rating: 9.1,
    reviewCount: 1234,
    features: ["19th Century", "Celebrity Hideout", "Hollywood History", "Riviera"],
    description: "Built in the 19th century, this celebrity hideout in Beaulieu has Hollywood history and timeless French Riviera glamour.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice"]
  },
  {
    id: 97,
    rank: 97,
    name: "Cowley Manor Twin Pools",
    hotel: "Cowley Manor Experimental",
    location: "Cotswolds",
    country: "UK",
    region: "Europe",
    image: "/images/pool-28.jpg",
    rating: 8.9,
    reviewCount: 2345,
    features: ["Indoor & Outdoor", "1970s Aesthetic", "Experimental Group", "Countryside"],
    description: "Rare for the UK - two pools, indoor and outdoor, at this glossy Experimental Group property with swirly seventies design throughout.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice", "Best UK Countryside Pool"]
  },
  {
    id: 98,
    rank: 98,
    name: "Albatroz Volcanic Pool",
    hotel: "Albatroz Beach & Yacht Club",
    location: "Santa Cruz, Madeira",
    country: "Portugal",
    region: "Europe",
    image: "/images/pool-9.jpg",
    rating: 8.8,
    reviewCount: 890,
    features: ["Volcanic Rock", "Natural Seawater", "Ocean-Fed", "Clifftop"],
    description: "One of the prettiest ocean pools in the world, naturally formed from volcanic rock and continuously filling with fresh ocean seawater.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice", "Best Natural Pool"]
  },
  {
    id: 99,
    rank: 99,
    name: "Belmond Reid's Palace Atlantic Pool",
    hotel: "Belmond Reid's Palace",
    location: "Funchal, Madeira",
    country: "Portugal",
    region: "Europe",
    image: "/images/pool-26.jpg",
    rating: 9.0,
    reviewCount: 3456,
    features: ["Cliff-Cut", "Atlantic Views", "Ocean Access", "Historic Palace"],
    description: "Cut into a cliff face with views over the Atlantic Ocean, featuring an exclusive pool terrace where you can walk down and jump straight into the ocean.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice"]
  },
  {
    id: 100,
    rank: 100,
    name: "Boucan Piton Pool",
    hotel: "Boucan by Hotel Chocolat",
    location: "Soufrière",
    country: "Saint Lucia",
    region: "Americas",
    image: "/images/pool-11.jpg",
    rating: 8.9,
    reviewCount: 567,
    features: ["Piton Views", "Cocoa Groves", "Rainforest", "Chocolate Martinis"],
    description: "Chocolate martinis served poolside overlooking the pointed peak of Petit Piton at this boutique property set in cocoa groves high in St Lucia's rainforest.",
    sources: ["Condé Nast Traveller"],
    awards: ["CNT Editors' Choice", "Most Indulgent Pool Experience"]
  },
  {
    id: 101,
    rank: 101,
    name: "Aquaventure Waterpark Pool",
    hotel: "Atlantis The Palm",
    location: "Palm Jumeirah",
    country: "UAE",
    region: "Middle East",
    image: "/images/pool-atlantis-dubai.jpg",
    rating: 9.3,
    reviewCount: 28450,
    features: ["Waterslide", "Shark Tank Slide", "Rapids", "Kid Friendly", "Aquarium"],
    description: "Home to the iconic Leap of Faith - a near-vertical waterslide that plunges through a shark-filled lagoon. Aquaventure features over 30 slides including the world's largest waterslide.",
    sources: ["TripAdvisor Travelers' Choice", "Travel + Leisure"],
    awards: ["World's Best Waterpark", "Most Thrilling Hotel Slides"],
    kidFriendly: true,
    websiteUrl: "https://www.atlantis.com/dubai/atlantis-aquaventure",
    bookingUrl: "https://www.atlantis.com/dubai/rooms-and-suites"
  },
  {
    id: 102,
    rank: 102,
    name: "Volcano Bay Wave Pool",
    hotel: "Universal's Cabana Bay Beach Resort",
    location: "Orlando, Florida",
    country: "USA",
    region: "Americas",
    image: "/images/pool-volcano-bay.jpg",
    rating: 9.2,
    reviewCount: 15670,
    features: ["Waterslide", "Wave Pool", "Lazy River", "Kid Friendly", "Volcano Theme"],
    description: "Direct access to Universal's Volcano Bay featuring the Ko'okiri Body Plunge - a 125-foot drop slide through a trap door, plus the Krakatau Aqua Coaster water roller coaster.",
    sources: ["TripAdvisor Travelers' Choice", "USA Today"],
    awards: ["Best Theme Park Waterslides", "Top Family Water Experience"],
    kidFriendly: true,
    websiteUrl: "https://www.universalorlando.com/web/en/us/hotels/cabana-bay-beach-resort",
    bookingUrl: "https://www.universalorlando.com/web/en/us/hotels/cabana-bay-beach-resort"
  },
  {
    id: 103,
    rank: 103,
    name: "Siam Park Pools",
    hotel: "Hard Rock Hotel Tenerife",
    location: "Costa Adeje, Tenerife",
    country: "Spain",
    region: "Europe",
    image: "/images/pool-siam-park.jpg",
    rating: 9.4,
    reviewCount: 8920,
    features: ["Waterslide", "Wave Pool", "Thai Theming", "Kid Friendly", "Tower of Power"],
    description: "Adjacent to Siam Park, voted the world's best waterpark multiple years running. Features the Tower of Power - a 28-meter vertical slide through a shark aquarium.",
    sources: ["TripAdvisor Travelers' Choice", "Condé Nast Traveler"],
    awards: ["World's Best Waterpark 2023-2025", "Best Themed Water Experience"],
    kidFriendly: true,
    websiteUrl: "https://www.hardrockhoteltenerife.com",
    bookingUrl: "https://www.hardrockhoteltenerife.com/en/offers"
  },
  {
    id: 104,
    rank: 104,
    name: "Waterbom Bali Pool Complex",
    hotel: "The Stones - Legian, Bali",
    location: "Kuta, Bali",
    country: "Indonesia",
    region: "Asia",
    image: "/images/pool-waterbom-bali.jpg",
    rating: 9.1,
    reviewCount: 12340,
    features: ["Waterslide", "Lazy River", "Kid Friendly", "Tropical Gardens", "Climax Slide"],
    description: "Steps from Asia's #1 waterpark, Waterbom Bali. The Climax slide features twin loops reaching speeds of 70 km/h, while the Smashdown 2.0 offers a thrilling free-fall experience.",
    sources: ["TripAdvisor Travelers' Choice", "Travel + Leisure Asia"],
    awards: ["Asia's Best Waterpark", "Top Family Resort Bali"],
    kidFriendly: true,
    websiteUrl: "https://www.stoneshotelbali.com",
    bookingUrl: "https://www.stoneshotelbali.com/offers"
  },
  {
    id: 105,
    rank: 105,
    name: "Cliffside Infinity Pool",
    hotel: "Le Sirenuse",
    location: "Positano",
    country: "Italy",
    region: "Europe",
    image: "/images/pool-le-sirenuse.jpg",
    rating: 9.7,
    reviewCount: 4890,
    features: ["Infinity Pool", "Sea Views", "Cliffside", "Historic Property", "Amalfi Coast"],
    description: "Perched high above Positano with towering staircase buildings marching up steep hillsides. The luminous green pool offers unmatched views of the sea below and expensive yachts anchored in the harbor. Refreshed in 2024 by a famous Italian artist.",
    sources: ["Condé Nast Traveller", "Travel + Leisure"],
    awards: ["One of the Best Hotels in the World", "Iconic Italian Pool"],
    websiteUrl: "https://sirenuse.it",
    bookingUrl: "https://sirenuse.it/en/book"
  },
  {
    id: 106,
    rank: 106,
    name: "Canyon Edge Pool",
    hotel: "Alila Jabal Akhdar",
    location: "Hajar Mountains",
    country: "Oman",
    region: "Middle East",
    image: "/images/pool-alila-oman.jpg",
    rating: 9.5,
    reviewCount: 2340,
    features: ["Infinity Pool", "Canyon Views", "Mountain", "Adventure Hotel", "Via Ferrata"],
    description: "Swimming above Oman's Grand Canyon with a sheer 3,000-foot drop just beyond the edge. Perched like a falcon on the lip of one of the deepest canyons in the world, in the high Hajar Mountains accessible only by 4WD.",
    sources: ["Condé Nast Traveller", "Travel + Leisure"],
    awards: ["Most Dramatic Pool Location", "Best Adventure Hotel Pool"],
    websiteUrl: "https://www.alilahotels.com/jabal-akhdar",
    bookingUrl: "https://www.alilahotels.com/jabal-akhdar"
  },
  {
    id: 107,
    rank: 107,
    name: "Surf View Pool",
    hotel: "Posada del Faro",
    location: "Jose Ignacio",
    country: "Uruguay",
    region: "Americas",
    image: "/images/pool-posada-faro.jpg",
    rating: 9.4,
    reviewCount: 1560,
    features: ["Infinity Pool", "Beach Views", "Boutique", "Surf", "Bohemian"],
    description: "A chalice-shaped pool surrounded by the hotel on two sides, with amphitheater views of perfect wave-dominated beaches. The sound of crashing surf creates the ultimate soundtrack, with a sunken self-serve bar built into the poolside.",
    sources: ["Travel + Leisure", "Departures"],
    awards: ["World's Best Beach Town Hotel", "Most Romantic Pool Setting"],
    websiteUrl: "https://www.posadadelfaro.com",
    bookingUrl: "https://www.posadadelfaro.com/en/reservations"
  },
  {
    id: 108,
    rank: 108,
    name: "Oyster Basin Pool",
    hotel: "La Co(o)rniche",
    location: "Pyla-sur-Mer",
    country: "France",
    region: "Europe",
    image: "/images/pool-la-coorniche.jpg",
    rating: 9.3,
    reviewCount: 3120,
    features: ["Infinity Pool", "Designer", "Philippe Starck", "Atlantic Views", "Dune du Pilat"],
    description: "Philippe Starck masterpiece perched on a pine-covered hilltop next to Europe's tallest sand dune. Watch the tides flow in and out of the Bassin d'Arcachon - home of France's best oysters - with sandy islands winking in and out. Everyone claps when the sun sets.",
    sources: ["Architectural Digest", "Condé Nast Traveller France"],
    awards: ["Best Designer Hotel Pool", "Most Unique French Pool"],
    websiteUrl: "https://lacoorniche.com",
    bookingUrl: "https://lacoorniche.com/en/book"
  }
]

// Hotel website URLs lookup - add real URLs for hotel outreach
const hotelUrls: Record<string, { websiteUrl: string; bookingUrl?: string }> = {
  "Grace Santorini": { websiteUrl: "https://www.gracehotels.com/santorini", bookingUrl: "https://www.gracehotels.com/santorini/reservations" },
  "Marina Bay Sands": { websiteUrl: "https://www.marinabaysands.com", bookingUrl: "https://www.marinabaysands.com/hotel/rooms-suites.html" },
  "Amankila": { websiteUrl: "https://www.aman.com/resorts/amankila", bookingUrl: "https://www.aman.com/resorts/amankila" },
  "Hotel du Cap-Eden-Roc": { websiteUrl: "https://www.oetkercollection.com/hotels/hotel-du-cap-eden-roc/", bookingUrl: "https://www.oetkercollection.com/hotels/hotel-du-cap-eden-roc/" },
  "Amangiri": { websiteUrl: "https://www.aman.com/resorts/amangiri", bookingUrl: "https://www.aman.com/resorts/amangiri" },
  "Monastero Santa Rosa Hotel & Spa": { websiteUrl: "https://www.monasterosantarosa.com", bookingUrl: "https://www.monasterosantarosa.com/en/offers/" },
  "Belmond Hotel Caruso": { websiteUrl: "https://www.belmond.com/hotels/europe/italy/amalfi-coast/belmond-hotel-caruso/", bookingUrl: "https://www.belmond.com/hotels/europe/italy/amalfi-coast/belmond-hotel-caruso/" },
  "Four Seasons Resort Bali at Sayan": { websiteUrl: "https://www.fourseasons.com/sayan/", bookingUrl: "https://www.fourseasons.com/sayan/" },
  "Hanging Gardens of Bali": { websiteUrl: "https://hanginggardensofbali.com", bookingUrl: "https://hanginggardensofbali.com/reservations/" },
  "Oberoi Udaivilas": { websiteUrl: "https://www.oberoihotels.com/hotels-in-udaipur-udaivilas-resort/", bookingUrl: "https://www.oberoihotels.com/hotels-in-udaipur-udaivilas-resort/" },
  "Six Senses Laamu": { websiteUrl: "https://www.sixsenses.com/en/resorts/laamu", bookingUrl: "https://www.sixsenses.com/en/resorts/laamu" },
  "Mandarin Oriental, Bangkok": { websiteUrl: "https://www.mandarinoriental.com/bangkok", bookingUrl: "https://www.mandarinoriental.com/bangkok" },
  "The Siam": { websiteUrl: "https://www.thesiamhotel.com", bookingUrl: "https://www.thesiamhotel.com" },
  "Belmond Copacabana Palace": { websiteUrl: "https://www.belmond.com/hotels/south-america/brazil/rio-de-janeiro/belmond-copacabana-palace/", bookingUrl: "https://www.belmond.com/hotels/south-america/brazil/rio-de-janeiro/belmond-copacabana-palace/" },
  "One&Only Cape Town": { websiteUrl: "https://www.oneandonlyresorts.com/cape-town", bookingUrl: "https://www.oneandonlyresorts.com/cape-town" },
  "Burj Al Arab Jumeirah": { websiteUrl: "https://www.jumeirah.com/en/stay/dubai/burj-al-arab-jumeirah", bookingUrl: "https://www.jumeirah.com/en/stay/dubai/burj-al-arab-jumeirah" },
  "The St. Regis Maldives": { websiteUrl: "https://www.marriott.com/hotels/travel/mlexr-the-st-regis-maldives-vommuli-resort/", bookingUrl: "https://www.marriott.com/hotels/travel/mlexr-the-st-regis-maldives-vommuli-resort/" },
  "Soneva Fushi": { websiteUrl: "https://soneva.com/resorts/soneva-fushi/", bookingUrl: "https://soneva.com/resorts/soneva-fushi/" },
  "Jade Mountain Resort": { websiteUrl: "https://www.jademountain.com", bookingUrl: "https://www.jademountain.com/reservations/" },
  "The Brando": { websiteUrl: "https://thebrando.com", bookingUrl: "https://thebrando.com/reservation/" },
  "Rosewood Hong Kong": { websiteUrl: "https://www.rosewoodhotels.com/en/hong-kong", bookingUrl: "https://www.rosewoodhotels.com/en/hong-kong" },
  "Park Hyatt Sydney": { websiteUrl: "https://www.hyatt.com/park-hyatt/sydph-park-hyatt-sydney", bookingUrl: "https://www.hyatt.com/park-hyatt/sydph-park-hyatt-sydney" },
  "Como Shambhala Estate": { websiteUrl: "https://www.comohotels.com/en/comoshambhalaestate", bookingUrl: "https://www.comohotels.com/en/comoshambhalaestate" },
  "Aman Tokyo": { websiteUrl: "https://www.aman.com/hotels/aman-tokyo", bookingUrl: "https://www.aman.com/hotels/aman-tokyo" },
  "Amanjena": { websiteUrl: "https://www.aman.com/resorts/amanjena", bookingUrl: "https://www.aman.com/resorts/amanjena" },
  "Four Seasons Resort Maui": { websiteUrl: "https://www.fourseasons.com/maui/", bookingUrl: "https://www.fourseasons.com/maui/" },
  "Hotel & Spa des Pecheurs": { websiteUrl: "https://hoteldespecheurs.com", bookingUrl: "https://hoteldespecheurs.com/en/reservation/" },
  "Canaves Oia Suites": { websiteUrl: "https://canaves.com/oia-suites/", bookingUrl: "https://canaves.com/oia-suites/" },
  "One&Only Reethi Rah": { websiteUrl: "https://www.oneandonlyresorts.com/reethi-rah", bookingUrl: "https://www.oneandonlyresorts.com/reethi-rah" },
  "Viceroy Bali": { websiteUrl: "https://www.viceroybali.com", bookingUrl: "https://www.viceroybali.com" },
  "COMO Cocoa Island": { websiteUrl: "https://www.comohotels.com/en/comocoocaisland", bookingUrl: "https://www.comohotels.com/en/comocoocaisland" },
  "Aman Venice": { websiteUrl: "https://www.aman.com/hotels/aman-venice", bookingUrl: "https://www.aman.com/hotels/aman-venice" },
  "SLS Dubai": { websiteUrl: "https://www.slshotels.com/dubai", bookingUrl: "https://www.slshotels.com/dubai" },
  "Address Beach Resort": { websiteUrl: "https://www.addresshotels.com/en/hotels/address-beach-resort/", bookingUrl: "https://www.addresshotels.com/en/hotels/address-beach-resort/" },
  "W Barcelona": { websiteUrl: "https://www.marriott.com/hotels/travel/bcnwh-w-barcelona/", bookingUrl: "https://www.marriott.com/hotels/travel/bcnwh-w-barcelona/" },
  "Badrutt's Palace Hotel": { websiteUrl: "https://www.badruttspalace.com", bookingUrl: "https://www.badruttspalace.com" },
  "Palace Luzern": { websiteUrl: "https://www.palace-luzern.ch/en/", bookingUrl: "https://www.palace-luzern.ch/en/" },
  "Emirates Palace Mandarin Oriental": { websiteUrl: "https://www.mandarinoriental.com/abu-dhabi/emirates-palace/luxury-hotel", bookingUrl: "https://www.mandarinoriental.com/abu-dhabi/emirates-palace/luxury-hotel" },
  "Taj Lake Palace": { websiteUrl: "https://www.tajhotels.com/en-in/taj/taj-lake-palace-udaipur/", bookingUrl: "https://www.tajhotels.com/en-in/taj/taj-lake-palace-udaipur/" },
  "Nihiwatu": { websiteUrl: "https://nihi.com", bookingUrl: "https://nihi.com/book/" },
  "Joali Maldives": { websiteUrl: "https://www.joali.com/joali-maldives/", bookingUrl: "https://www.joali.com/joali-maldives/" },
  "Atlantis The Royal": { websiteUrl: "https://www.atlantis.com/atlantis-the-royal", bookingUrl: "https://www.atlantis.com/atlantis-the-royal" },
  "Mondrian Singapore": { websiteUrl: "https://www.sbe.com/hotels/mondrian/singapore", bookingUrl: "https://www.sbe.com/hotels/mondrian/singapore" },
  "Graduate Tucson": { websiteUrl: "https://www.graduatehotels.com/tucson/", bookingUrl: "https://www.graduatehotels.com/tucson/" },
  "Bisma Eight": { websiteUrl: "https://www.bismaeight.com", bookingUrl: "https://www.bismaeight.com" },
  "Grand Hotel Tremezzo": { websiteUrl: "https://www.grandhoteltremezzo.com", bookingUrl: "https://www.grandhoteltremezzo.com/en/book-now/" },
  "Daios Cove Luxury Resort": { websiteUrl: "https://www.daioscove.com", bookingUrl: "https://www.daioscove.com/book-now/" },
  "Amanruya": { websiteUrl: "https://www.aman.com/resorts/amanruya", bookingUrl: "https://www.aman.com/resorts/amanruya" },
  "Castello di Vicarello": { websiteUrl: "https://www.castellodivicarello.com", bookingUrl: "https://www.castellodivicarello.com/book/" },
  "The Bodrum Edition": { websiteUrl: "https://www.marriott.com/hotels/travel/bjved-the-bodrum-edition/", bookingUrl: "https://www.marriott.com/hotels/travel/bjved-the-bodrum-edition/" },
  "Nobu Hotel Ibiza Bay": { websiteUrl: "https://www.nobuhotelibizabay.com", bookingUrl: "https://www.nobuhotelibizabay.com/reservations" },
  "Alila Ubud": { websiteUrl: "https://www.alilahotels.com/ubud", bookingUrl: "https://www.alilahotels.com/ubud" },
  "Castello di Reschio": { websiteUrl: "https://www.reschio.com", bookingUrl: "https://www.reschio.com/book/" },
  "The Dolli at Athens": { websiteUrl: "https://www.grecotel.com/hotels/the-dolli", bookingUrl: "https://www.grecotel.com/hotels/the-dolli" },
  "Soho Warehouse": { websiteUrl: "https://www.sohohouse.com/houses/soho-warehouse", bookingUrl: "https://www.sohohouse.com/houses/soho-warehouse" },
  "Cali Mykonos": { websiteUrl: "https://www.calimykonos.com", bookingUrl: "https://www.calimykonos.com/booking" },
  "Cap Rocat": { websiteUrl: "https://www.caprocat.com", bookingUrl: "https://www.caprocat.com/en/reservations/" },
  "25hours Hotel One Central": { websiteUrl: "https://www.25hours-hotels.com/hotels/dubai/one-central", bookingUrl: "https://www.25hours-hotels.com/hotels/dubai/one-central" },
  "Singita Sweni Lodge": { websiteUrl: "https://singita.com/lodge/sweni-lodge/", bookingUrl: "https://singita.com/lodge/sweni-lodge/" },
  "Hotel Santa Caterina": { websiteUrl: "https://www.hotelsantacaterina.it", bookingUrl: "https://www.hotelsantacaterina.it/en/book/" },
  "Chapung SeBali Resort and Spa": { websiteUrl: "https://www.chapung.com", bookingUrl: "https://www.chapung.com/book-now/" },
  "Capella Ubud": { websiteUrl: "https://www.capellahotels.com/en/capella-ubud", bookingUrl: "https://www.capellahotels.com/en/capella-ubud" },
  "Six Senses Zil Pasyon": { websiteUrl: "https://www.sixsenses.com/en/resorts/zil-pasyon", bookingUrl: "https://www.sixsenses.com/en/resorts/zil-pasyon" },
  "Wild Coast Tented Lodge": { websiteUrl: "https://www.resplendentceylon.com/wildcoasttentedlodge", bookingUrl: "https://www.resplendentceylon.com/wildcoasttentedlodge" },
  "Qualia": { websiteUrl: "https://www.qualia.com.au", bookingUrl: "https://www.qualia.com.au/book" },
  "The Berkeley": { websiteUrl: "https://www.the-berkeley.co.uk", bookingUrl: "https://www.the-berkeley.co.uk/book/" },
  "Six Senses Yao Noi": { websiteUrl: "https://www.sixsenses.com/en/resorts/yao-noi", bookingUrl: "https://www.sixsenses.com/en/resorts/yao-noi" },
  "Le Bristol Paris": { websiteUrl: "https://www.oetkercollection.com/hotels/le-bristol-paris/", bookingUrl: "https://www.oetkercollection.com/hotels/le-bristol-paris/" },
  "Alila Villas Uluwatu": { websiteUrl: "https://www.alilahotels.com/uluwatu", bookingUrl: "https://www.alilahotels.com/uluwatu" },
  "Il Sereno": { websiteUrl: "https://www.ilsereno.com", bookingUrl: "https://www.ilsereno.com/en/book/" },
  "The Chedi Muscat": { websiteUrl: "https://www.ghmhotels.com/en/muscat/", bookingUrl: "https://www.ghmhotels.com/en/muscat/" },
  "Four Seasons Resort Koh Samui": { websiteUrl: "https://www.fourseasons.com/kohsamui/", bookingUrl: "https://www.fourseasons.com/kohsamui/" },
  "Amanpuri": { websiteUrl: "https://www.aman.com/resorts/amanpuri", bookingUrl: "https://www.aman.com/resorts/amanpuri" },
  "Four Seasons The Nam Hai": { websiteUrl: "https://www.fourseasons.com/hoian/", bookingUrl: "https://www.fourseasons.com/hoian/" },
  "Fregate Island Private": { websiteUrl: "https://www.fregate.com", bookingUrl: "https://www.fregate.com/book-now/" },
  "Joali": { websiteUrl: "https://www.joali.com/joali-maldives/", bookingUrl: "https://www.joali.com/joali-maldives/" },
  "Alila Kothaifaru Maldives": { websiteUrl: "https://www.alilahotels.com/kothaifaru-maldives", bookingUrl: "https://www.alilahotels.com/kothaifaru-maldives" },
  "Borgo Pignano": { websiteUrl: "https://www.borgopignano.com", bookingUrl: "https://www.borgopignano.com/book/" },
  "Erosantorini": { websiteUrl: "https://www.erosantorini.com", bookingUrl: "https://www.erosantorini.com/book/" },
  "Villa Althea": { websiteUrl: "https://www.villaalthea.gr", bookingUrl: "https://www.villaalthea.gr" },
  "Tierra Atacama": { websiteUrl: "https://www.tierrahotels.com/atacama/", bookingUrl: "https://www.tierrahotels.com/atacama/" },
  "Omaanda by Zannier Hotels": { websiteUrl: "https://www.zannierhotels.com/omaanda", bookingUrl: "https://www.zannierhotels.com/omaanda" },
  "Miramonti Boutique Hotel": { websiteUrl: "https://www.hotel-miramonti.com", bookingUrl: "https://www.hotel-miramonti.com/en/book/" },
  "Hotel Oderberger": { websiteUrl: "https://www.hotel-oderberger.berlin", bookingUrl: "https://www.hotel-oderberger.berlin/en/book/" },
  "Manon Les Suites": { websiteUrl: "https://www.manonlessuites.com", bookingUrl: "https://www.manonlessuites.com/book-now/" },
  "Sun Gardens Dubrovnik": { websiteUrl: "https://www.sungardensdubrovnik.com", bookingUrl: "https://www.sungardensdubrovnik.com/book-now/" },
  "Amansara": { websiteUrl: "https://www.aman.com/hotels/amansara", bookingUrl: "https://www.aman.com/hotels/amansara" },
  "Chiva Som": { websiteUrl: "https://www.chivasom.com", bookingUrl: "https://www.chivasom.com/book-now/" },
  "Phum Baitang": { websiteUrl: "https://www.phumbaitang.com", bookingUrl: "https://www.phumbaitang.com/book-now/" },
  "La Reserve de Beaulieu": { websiteUrl: "https://www.lareserve-beaulieu.com", bookingUrl: "https://www.lareserve-beaulieu.com/en/book/" },
  "Cowley Manor Experimental": { websiteUrl: "https://www.cowleymanor.com", bookingUrl: "https://www.cowleymanor.com/book-now/" },
  "Albatroz Beach & Yacht Club": { websiteUrl: "https://www.albatrozbeachyachtclub.com", bookingUrl: "https://www.albatrozbeachyachtclub.com" },
  "Belmond Reid's Palace": { websiteUrl: "https://www.belmond.com/hotels/europe/portugal/madeira/belmond-reids-palace/", bookingUrl: "https://www.belmond.com/hotels/europe/portugal/madeira/belmond-reids-palace/" },
  "Boucan by Hotel Chocolat": { websiteUrl: "https://www.hotelchocolat.com/uk/boucan.html", bookingUrl: "https://www.hotelchocolat.com/uk/boucan.html" },
  "Atlantis The Palm": { websiteUrl: "https://www.atlantis.com/dubai", bookingUrl: "https://www.atlantis.com/dubai/rooms-and-suites" },
  "Universal's Cabana Bay Beach Resort": { websiteUrl: "https://www.universalorlando.com/web/en/us/hotels/cabana-bay-beach-resort", bookingUrl: "https://www.universalorlando.com/web/en/us/hotels/cabana-bay-beach-resort" },
  "Hard Rock Hotel Tenerife": { websiteUrl: "https://www.hardrockhoteltenerife.com", bookingUrl: "https://www.hardrockhoteltenerife.com/en/offers" },
  "The Stones - Legian, Bali": { websiteUrl: "https://www.stoneshotelbali.com", bookingUrl: "https://www.stoneshotelbali.com/offers" },
  "Le Sirenuse": { websiteUrl: "https://sirenuse.it", bookingUrl: "https://sirenuse.it/en/book" },
  "Alila Jabal Akhdar": { websiteUrl: "https://www.alilahotels.com/jabal-akhdar", bookingUrl: "https://www.alilahotels.com/jabal-akhdar" },
  "Posada del Faro": { websiteUrl: "https://www.posadadelfaro.com", bookingUrl: "https://www.posadadelfaro.com/en/reservations" },
  "La Co(o)rniche": { websiteUrl: "https://lacoorniche.com", bookingUrl: "https://lacoorniche.com/en/book" },
}

// Add kidFriendly, websiteUrl, and slug to pools
const poolsWithExtras = pools.map(pool => {
  const urls = hotelUrls[pool.hotel] || {
    websiteUrl: pool.websiteUrl || `https://www.google.com/search?q=${encodeURIComponent(pool.hotel + ' official website')}`,
    bookingUrl: pool.bookingUrl
  }
  return {
    ...pool,
    slug: generateSlug(pool.hotel, pool.id),
    kidFriendly: pool.kidFriendly ?? !pool.features.includes("Adults Only"),
    websiteUrl: pool.websiteUrl || urls.websiteUrl,
    bookingUrl: pool.bookingUrl || urls.bookingUrl
  }
}) as Pool[]

export { poolsWithExtras as pools }

export const regions = [
  { name: "All Regions", count: poolsWithExtras.length },
  { name: "Europe", count: poolsWithExtras.filter(p => p.region === "Europe").length },
  { name: "Asia", count: poolsWithExtras.filter(p => p.region === "Asia").length },
  { name: "Americas", count: poolsWithExtras.filter(p => p.region === "Americas").length },
  { name: "Africa", count: poolsWithExtras.filter(p => p.region === "Africa").length },
  { name: "Middle East", count: poolsWithExtras.filter(p => p.region === "Middle East").length },
  { name: "Oceania", count: poolsWithExtras.filter(p => p.region === "Oceania").length }
]

export const countries = [...new Set(poolsWithExtras.map(p => p.country))].sort()

export const continents = ["All Regions", "Europe", "Asia", "Americas", "Africa", "Middle East", "Oceania"]

export const features = [
  "Infinity Edge",
  "Rooftop",
  "Private",
  "Heated",
  "Ocean View",
  "Mountain View",
  "Adults Only",
  "Spa",
  "Indoor/Outdoor",
  "Historic",
  "Desert Setting",
  "Jungle View",
  "City Skyline",
  "Lake View",
  "Waterslide",
  "Kid Friendly"
]

export const sortOptions = [
  { value: "rank", label: "Top Ranked" },
  { value: "rating", label: "Highest Rated" },
  { value: "reviews", label: "Most Reviewed" },
  { value: "name", label: "Name A-Z" }
]
